"""
config_manager.py
------------------
Covers Requirement 3 (Configuration Handling):
  - loads/saves user preferences (user_config.json)
  - resolves and writes out an env file (env.sh / env.bat) exporting
    PATH entries and tool locations so eSim can find each tool without
    the user manually editing shell profiles.
"""

import json
import os
import shutil
import platform

from tool_manager.utils.system_utils import which
from tool_manager.core.logger import get_logger

logger = get_logger(__name__)

USER_CONFIG_PATH = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), "config", "user_config.json"
)


class ConfigManager:
    def __init__(self, config_path: str = USER_CONFIG_PATH):
        self.config_path = config_path
        self.config = self._load()

    def _load(self) -> dict:
        with open(self.config_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def save(self):
        with open(self.config_path, "w", encoding="utf-8") as f:
            json.dump(self.config, f, indent=2)
        logger.info(f"Saved user configuration to {self.config_path}")

    def get(self, key: str, default=None):
        return self.config.get(key, default)

    def set(self, key: str, value):
        self.config[key] = value
        self.save()

    def install_root(self) -> str:
        return os.path.expanduser(self.config.get("install_root", "~/.esim/tools"))

    def env_file_path(self) -> str:
        return os.path.expanduser(self.config.get("esim_env_file", "~/.esim/env.sh"))

    def resolve_tool_paths(self, tool_names: list, installer=None) -> dict:
        """
        Finds the on-disk binary location for each tool (best effort).
        Uses the registry's explicit 'binary' field (falls back to the
        tool's registry key if not specified, since not every tool's
        binary matches its registry name -- e.g. 'ngveri' -> 'ghdl').
        """
        found = {}
        for name in tool_names:
            binary = name
            if installer is not None:
                meta = installer.get_tool_meta(name)
                binary = meta.get("binary", name)
            found[name] = which(binary)
        return found

    def write_env_file(self, tool_paths: dict):
        """
        Writes a small shell script exporting PATH additions for every
        located tool, so eSim (or the user's shell) can `source` it.
        On Windows, writes a .bat equivalent instead.
        """
        is_windows = platform.system().lower().startswith("win")
        env_path = self.env_file_path()
        if is_windows and env_path.endswith(".sh"):
            env_path = env_path[:-3] + ".bat"

        os.makedirs(os.path.dirname(env_path), exist_ok=True)

        lines = []
        if is_windows:
            lines.append("@echo off")
            lines.append(":: Auto-generated by eSim Tool Manager")
            for name, path in tool_paths.items():
                if path:
                    tool_dir = os.path.dirname(path)
                    lines.append(f'set PATH=%PATH%;{tool_dir}')
        else:
            lines.append("#!/usr/bin/env bash")
            lines.append("# Auto-generated by eSim Tool Manager")
            for name, path in tool_paths.items():
                if path:
                    tool_dir = os.path.dirname(path)
                    lines.append(f'export PATH="{tool_dir}:$PATH"')

        with open(env_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

        if not is_windows:
            os.chmod(env_path, 0o755)

        logger.info(f"Wrote environment configuration to {env_path}")
        return env_path
